services:
  user_db:
    image: postgres:14
    container_name: dnd_tracker_user_db
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "35432:5432"
    volumes:
      - dnd_tracker_user_db:/var/lib/postgresql
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_POSTGRES_USER} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  user_service:
    build: .
    container_name: dnd_tracker_user_service
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      user_db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  dnd_tracker_user_db:
